server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /
    username: guest
    password: guest
    host: 127.0.0.1

leyou:
  sms:
    accessKeyId: LTAIc259TULYzaS7  # 你自己的accessKeyId
    accessKeySecret: 1uh79I1UAmwQ4YWsSmOgxw7JEBGA0v # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_148614415 # 模板名称