server:
  port: 10011
spring:
  application:
    name: leyou-config
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/lyj8330328/leyou-config.git
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    virtual-host: /


management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
